### ISSUE TITLE
`sbt run` not working

### ISSUE THREAD

**Issue by leeshangqian** [pauljamescleary/scala-pet-store#105]
When using `sbt run` to start the project, it appears that `pureconfig.loadConfig` cannot find the `reference.conf` file. It complains that the `petstore` key is missing even though it's there.

```
pureconfig.error.ConfigReaderException: Cannot convert configuration to a io.github.pauljamescleary.petstore.config.PetStoreConfig. Failures are:
  at the root:
    - Key not found: 'petstore'.
```

**Comment by pauljamescleary** [comment]
Thanks @leeshangqian this is a strange issue for sure.  I found the same thing.  Wonder if it is some kind of strange library version issue under the hood.

**Comment by nebtrx** [comment]
FYI, I can't reproduce it

**Comment by zakpatterson** [comment]
I'm still seeing it, here's the full trace:

```
⟩ sbt run
[info] Loading settings for project global-plugins from idea.sbt,sbt-updates.sbt,plugins.sbt,metals.sbt ...
[info] Loading global plugins from /Users/zak/.sbt/1.0/plugins
[info] Loading settings for project scala-pet-store-build from plugins.sbt ...
[info] Loading project definition from /Users/zak/projects/clovellytech/oss/scala-pet-store/project
[info] Loading settings for project scala-pet-store from build.sbt ...
[info] Set current project to scala-pet-store (in build file:/Users/zak/projects/clovellytech/oss/scala-pet-store/)
[info] Compiling 2 Scala sources to /Users/zak/projects/clovellytech/oss/scala-pet-store/target/scala-2.12/classes ...
[info] Done compiling.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/zak/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.6/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Packaging /Users/zak/projects/clovellytech/oss/scala-pet-store/target/scala-2.12/scala-pet-store_2.12-0.0.1-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running io.github.pauljamescleary.petstore.Server 
pureconfig.error.ConfigReaderException: Cannot convert configuration to a io.github.pauljamescleary.petstore.config.PetStoreConfig. Failures are:
  at the root:
    - Key not found: 'petstore'.

	at io.github.pauljamescleary.petstore.config.PetStoreConfig$.$anonfun$load$3(PetStoreConfig.scala:20)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:137)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:36)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:33)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:328)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:117)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 7 s, completed Dec 27, 2018, 10:53:44 PM
```

**Comment by pauljamescleary** [comment]
@zakpatterson yea, this is basically the resolution of the default typesafe config failing for some odd reason.  We are also seeing this in https://github.com/vinyldns/vinyldns 

It's like it cannot find application.conf with fallback to reference.conf for some reason

**Comment by zakpatterson** [comment]
Correct, if you look at what is resolved at run time, even in the repl, I've seen an enormous datastructure which I guess is the default config. I'm not seeing this in a couple other projects, I'll take another stab at trying to figure out what's different.

**Comment by pauljamescleary** [comment]
@zakpatterson yes, I am thinking are the `reference.conf` from basically all the libs we use

**Comment by pauljamescleary** [comment]
I have a hack/workaround in at least with #109, the trick was to fork in run :/
