### ISSUE TITLE
`UserEndpointsSpec` specs are not been executed

### ISSUE THREAD

**Issue by nebtrx** [pauljamescleary/scala-pet-store#91]
Firstable, excellent job with this sort of toy/teaching project. I love it! 🙌

Having said that, I can go  straight to bussiness😁

I noticed none of the `UserEndpointsSpec` specs are been executed. If you take a closer look [here](https://github.com/pauljamescleary/scala-pet-store/blob/066489e8ba40ea76ae397fb0b5842e101775ada3/src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala#L35-L43), the for comprehension corresponds to an `IO[Assertion]` computation which never gets executed.  That actually doesn't happen in the rest of the endpoints specs, which execute the computation by calling `unsafeRunSync`.

I'm trying to push a PR fixing it but I'm getting two weird  `http4s-circe` decoding errors. I'm not sure why those are happening because standalone `circe` decodes both examples perfectly

Here are the errors:

1. The first one, if I use the arbitrary instance generation for `User` case class
```
InvalidMessageBodyFailure was thrown during property evaluation.
[info]     Message: Invalid message body: Could not decode JSON: {
[info]     "userName" : "",
[info]     "firstName" : "",
[info]     "lastName" : "",
[info]     "email" : "",
[info]     "hash" : "",
[info]     "phone" : "",
[info]     "id" : 1
[info]   }
[info]     Occurred when passed generated values (
[info]       arg0 = User(,,,,,,Some(1))
[info]     )
```
2. The second one, If I use the [user value](https://github.com/pauljamescleary/scala-pet-store/blob/066489e8ba40ea76ae397fb0b5842e101775ada3/src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala#L33) provided in the code
```
org.http4s.InvalidMessageBodyFailure: Invalid message body: Could not decode JSON: {
[info]   "userName" : "username",
[info]   "firstName" : "firstname",
[info]   "lastName" : "lastname",
[info]   "email" : "email",
[info]   "hash" : "password",
[info]   "phone" : "phone",
[info]   "id" : null
[info] }
[info]   at org.http4s.circe.CirceInstances.$anonfun$jsonOf$2(CirceInstances.scala:55)
[info]   at scala.util.Either.fold(Either.scala:189)
[info]   at org.http4s.circe.CirceInstances.$anonfun$jsonOf$1(CirceInstances.scala:56)
[info]   at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:87)
[info]   at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:207)
[info]   at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:207)
[info]   at cats.effect.IO.unsafeRunTimed(IO.scala:304)
[info]   at cats.effect.IO.unsafeRunSync(IO.scala:239)
[info]   at io.github.pauljamescleary.petstore.infrastructure.endpoint.UserEndpointsSpec.$anonfun$new$1(UserEndpointsSpec.scala:37)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   ...
[info]   Cause: io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(password)
```

I think someone else ran into the first issue before. He must have tried to fix it using a fixed value for the `User` case class but forgot to execute the computation and therefore the spec turned successful when it was actually broken. All this is just speculation on my end.

I'll take a closer look at `http4s-circe` code later to check if I can spot the issue. Meanwhile, if someone has a clue on this I'll be glad to listen/reading about it in order to fix the issue.

**Comment by nebtrx** [comment]
@pauljamescleary the issue is because the user endpoints specs are expecting a `User` value in the `createRequest` at the beginning of each spec instead of a `SignupRequest`. That was tricky to spot because both case classes are almost identical, except for the **id** field

I already fixed it in a local branch. Aside from that, there are a couple of other minor issues regarding the username arbitrary instances in the **get user by userName** spec. Working on those too so you can expect a PR soon(Two days top, it depens on my next spare time window)
